title: My Awesome Blog
author: Shehriyar Shariq
email: sshariq.bscs18seecs@seecs.edu.pk
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog. Here I'll write about my life, my job and my career goals.
  Feel free to follow up on my updates by subscribing to my newletter. Cheers!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
